### ISSUE TITLE
--smart/-S has been removed.  Use +smart or -smart extension instead.

### ISSUE THREAD

**Issue by Fankbai** [mschroen/science.md#5]
```shell
$ make -s all
| cat content/*.md > release/Markdown_theme.md
>  3.8K release/Markdown_theme.md
i Less than 595 words
| sed s/==XX comment==/[XX] comment/ release/Markdown_theme.md
| pandoc release/Markdown_theme.md -o release/Markdown_theme.html
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc.exe --help for more information.
Makefile:93: recipe for target 'html' failed
make: *** [html] Error 2
```
_____________________________________________________________________________
from this [link[(https://github.com/rstudio/rmarkdown/issues/1120), the answer is XXX doesn't support pandoc 2.0

which version should i use?

could you upgrade this pro?

thanks bro. love your work.

**Comment by mschroen** [comment]
Thanks for the hint. [Pandoc 2.x came with a huge update of the syntax and is more strict](https://pandoc.org/releases.html#pandoc-2.0-29-oct-2017). If you have pandoc 2.x, remember to also [update pandoc-crossref](https://github.com/lierdakil/pandoc-crossref/releases).

So I updated Science.md which is now compatible. Enjoy!

**Comment by mschroen** [comment]
Solved with https://github.com/mschroen/Science.md/commit/3008bac8b690e431b9382799ad068b1552a4ef13 .
